### ISSUE TITLE
Optional phone number

### ISSUE THREAD

**Issue by pgsill** [tepez/joi-phone-number-extensions#2]
Is it possible to make it so inputting a phone number is optional? Not providing a phone number always fails validation, even if I didn't add `.required()`.

```js
const schema = Joi.object().keys({
  name: Joi.string()
    .min(3)
    .required(),
  email: Joi.string()
    .email()
    .required(),
  birthday: Joi.date(),
  landline: Joi.phoneNumber().defaultRegion('BR').type('FIXED_LINE').format('E164'),
  mobile: Joi.phoneNumber().defaultRegion('BR').type('MOBILE').format('E164'),
});
```

In this scenario, I want `landline` to be optional and `mobile` to be mandatory. Is this possible? I couldn't find a way to make it work. Thanks!

**Comment by tomyam1** [comment]
I just added specs to confirm it's working as expected.
Maybe you need to add `.allow(null)` to your schema.
